<a href="https://colab.research.google.com/github/Loukika1502/2400520082/blob/main/python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
try:
  a = int(input("Enter First number:"))
  b = int(input("Enter second number"))
  result = a/b
  print("Result:",result)
except ZeroDivisionError:
  print("Cannot divide by zero")

Enter First number:5
Enter second number6
Result: 0.8333333333333334


In [ ]:
try:
  num = int(input("Enter a number:"))
  print("Number:",num)
except ValueError:
  print("Invalid input!please enter a number.")

Enter a number:8
Number: 8


In [ ]:
try:
  a = int(input("Enter first number:"))
  b = int(input("Enter second number:"))
  print("Result:",a / b)
except ValueError:
  print("please enter numbers only.")
except ZeroDivisionError:
  print("Cannot divide by zero.")

Enter first number:9
Enter second number:8
Result: 1.125


In [ ]:
try:
    a = int(input("Enter first number: "))
    b = int(input("Enter second number: "))
    op = input("Enter operator (+, -, *, /): ")

    if op == "+":
        result = a + b
    elif op == "-":
        result = a - b
    elif op == "*":
        result = a * b
    elif op == "/":
        result = a / b
    else:
        print("Invalid operator")
        result = None

except ValueError:
    print("Invalid input")

except ZeroDivisionError:
    print("Cannot divide by zero")

else:
    print("Result:", result)

finally:
    print("Calculator program completed")

Enter first number: 5
Enter second number: 3
Enter operator (+, -, *, /): -
Result: 2
Calculator program completed


In [ ]:
try:
    file = open("student.txt", "r")
    print(file.read())
    file.close()
except FileNotFoundError:
    print("File not found")

File not found


In [ ]:
class InvalidAgeError(Exception):
    pass

try:
    age = int(input("Enter your age: "))

    if age < 18:
        raise InvalidAgeError("Age must be 18 or above")

    print("Valid age")

except InvalidAgeError as e:
    print(e)

Enter your age: 22
Valid age


In [ ]:
class InsufficientBalanceError(Exception):
    pass

balance = 1000

try:
    amount = int(input("Enter withdrawal amount: "))

    if amount > balance:
        raise InsufficientBalanceError("Insufficient bank balance")

    balance = balance - amount
    print("Remaining balance:", balance)

except InsufficientBalanceError as e:
    print(e)

Enter withdrawal amount: 500
Remaining balance: 500


In [ ]:
name = input("Enter student name: ")
age = input("Enter student age: ")
course = input("Enter course: ")

file = open("student.txt", "w")
file.write("Name: " + name + "\n")
file.write("Age: " + age + "\n")
file.write("Course: " + course + "\n")
file.close()

print("Student details saved")

Enter student name: N.loukika
Enter student age: 12
Enter course: 4
Student details saved


In [ ]:
file = open("student.txt", "r")

data = file.read()
print(data)

file.close()

Name: N.loukika
Age: 12
Course: 4



In [ ]:
name = input("Enter student name: ")
age = input("Enter student age: ")
course = input("Enter course: ")

file = open("student.txt", "a")

file.write("\nName: " + name + "\n")
file.write("Age: " + age + "\n")
file.write("Course: " + course + "\n")

file.close()

print("Student details added")

Enter student name: N.Rahul kumar
Enter student age: 23
Enter course: 5
Student details added


In [ ]:
file = open("student.txt", "r")

lines = file.readlines()

print("Number of lines:", len(lines))

file.close()

Number of lines: 7


In [ ]:
file = open("student.txt", "r")

data = file.read()
words = data.split()

print("Number of words:", len(words))

file.close()

Number of words: 13


In [ ]:
file = open("student.txt", "r")

data = file.read()

print("Number of characters:", len(data))

file.close()

Number of characters: 73


In [ ]:
word = input("Enter word to search: ")

file = open("student.txt", "r")
data = file.read()

if word in data:
    print("Word found")
else:
    print("Word not found")

file.close()

Enter word to search: Rahul
Word found


In [ ]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

print(arr)

[10 20 30 40 50]


In [ ]:
import numpy as np

zeros = np.zeros(5)
ones = np.ones(5)

print("Zeros:", zeros)
print("Ones:", ones)

Zeros: [0. 0. 0. 0. 0.]
Ones: [1. 1. 1. 1. 1.]


In [ ]:
import numpy as np

arr = np.arange(1, 11)

print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
import numpy as np

a = np.array([10, 20, 30])
b = np.array([2, 4, 5])

print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)

Addition: [12 24 35]
Subtraction: [ 8 16 25]
Multiplication: [ 20  80 150]
Division: [5. 5. 6.]


In [ ]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

print("Sum:", np.sum(arr))
print("Mean:", np.mean(arr))
print("Maximum:", np.max(arr))
print("Minimum:", np.min(arr))

Sum: 150
Mean: 30.0
Maximum: 50
Minimum: 10


In [ ]:
import numpy as np

arr = np.arange(1, 10)

new_arr = arr.reshape(3, 3)

print(new_arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
